Job 1 map reduce

map(row)
        Input: a row of the input file;

        fields <- split row by "\t"
        time <- field time in row
        summary <-- field summary in row
        year <- convert time from unix time to string
        for each word in summary
            key <- year + "\t" + word
            return(key,1)

reduce(key, values)
        Input: key: key from map passage ( year word)
        values: list of values related to the key ({1,1,..,1})

        fields <- split key by "\t"
        year <- field year in a single value
        word <- field word in a single value
        for each 1 in values sums their in sum

        if (!map.containsKey(year))
            mvMap<-- new MultiValueMap(key=sum, value=word)
            map.put(year,mvMap)

        else
            map.get(year).put(sum,word)


cleanup(map)
        Input: map with key = year and value = word and its occurence
        for each year in map
                order the words by number of occurence
                retrive and print the first 10

job 2

map(row)
        Input: a row of the input file;

        fields <- split row by "\t"
        time <- field time in row
        productId <-- field productId in row
        score <-- field score in row
        year <- convert time from unix time to string
        key <- year + "\t" + productId
        return(key,score)

reduce(key,values)
        Input: key: key from map passage ( year productId)
        values: list score related to the key

        averageScore <-- average of values
        year <- field year in a single value
        productId <-- field productId in a single value
        if  2002 < year < 2013
            if (map.containsKey(productID))
                mvMap <-- new MultiValueMap(key=averageScore, value=year)
                map.put(productID,mvMap);
            else
                map.get(productID).put(averageScore,year)

cleanup(map)
        Input: map with key = product and value = year and average score

        for each product in map
            print year and it averageScore


Job 3

    map1(row)
        Input: a row of the input file;

        fields <- split row by "\t"
        productId <-- field productId in row
        userId <-- field userId in row
        return(userId,productId)

    reduce1(key, values)
        Input: key: key from map passage (userId)
        values: list of products reviewed by userId(key)

        products<-- list of all product in values
        for each product in products
            couple<-- couple of distinct product rewied by the user
            return(couple,userId)


    map2(row)
        Input: a row of the input file generated by reduce1 (couple of product, user)
        fields <- split row by "\t"
        product1<-- field product1 in row
        product2<-- field product2 in row
        key<-- product1 "\t" product2
        return (key,1)

    reduce2(key, values)
        Input: key: key from map passage ( product1 product2)
        values: list of values realted to the key ({1,1,..,1})

        for each 1 in values sums their in sum
        return(key,sum)



